export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST"
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS"
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL"

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST"
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS"
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL"

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST"
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS"
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL"
export const ORDER_PAY_RESET = "ORDER_PAY_RESET"

export const MY_ORDER_LIST_REQUEST = "MY_ORDER_LIST_REQUEST"
export const MY_ORDER_LIST_SUCCESS = "MY_ORDER_LIST_SUCCESS"
export const MY_ORDER_LIST_FAIL = "MY_ORDER_LIST_FAIL"

export const MY_ORDER_LIST_RESET = "MY_ORDER_LIST_RESET"


export const ORDERS_LIST_REQUEST = "ORDERS_LIST_REQUEST"
export const ORDERS_LIST_SUCCESS = "ORDERS_LIST_SUCCESS"
export const ORDERS_LIST_FAIL = "ORDERS_LIST_FAIL"

export const AMOUNT_PAID_REQUEST = "AMOUNT_PAID_REQUEST"
export const AMOUNT_PAID_SUCCESS = "AMOUNT_PAID_SUCCESS"
export const AMOUNT_PAID_FAIL = "AMOUNT_PAID_FAIL"

export const ORDER_DELIVERED_REQUEST = "ORDER_DELIVERED_REQUEST"
export const ORDER_DELIVERED_SUCCESS = "ORDER_DELIVERED_SUCCESS"
export const ORDER_DELIVERED_FAIL = "ORDER_DELIVERED_FAIL"